/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tettoon_pipara_PiParaJni */

#ifndef _Included_tettoon_pipara_PiParaJni
#define _Included_tettoon_pipara_PiParaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tettoon_pipara_PiParaJni
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tettoon_pipara_PiParaJni_setup
  (JNIEnv *, jobject);

/*
 * Class:     tettoon_pipara_PiParaJni
 * Method:    write
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_tettoon_pipara_PiParaJni_write
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
